# Site settings
title: Shane Weaver 2019
email: shanebweaver@gmail.com
description: Engineer + Entrepreneur
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Shane Weaver
your-title: Engineer + Entrepreneur

# Social settings
500px_url:
facebook_url: https://www.facebook.com/shane.weaver
github_url: https://github.com/shanebweaver
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/shanebweaver
linkedin_url: https://www.linkedin.com/in/shanebweaver
pinterest_url:
slack_url:
twitter_url: https://twitter.com/shanebweaver
blog_url: http://www.mycoblog.com

# Build settings
markdown: kramdown
